Add policy related perms to RPK User
I tested the minimum required permissions for the rpk user as of
today. (Hadn't tested them in a while.) And discovered that
these two permissions were missing.

Resulting errors looked like:

```
Error: creating IAM Policy... is not authorized to perform: iam:CreatePolicy
Error: creating IAM Policy... is not authorized to perform: iam:TagPolicy
```